spring:
  datasource:
    url: jdbc:mysql://localhost:3306/search_engine?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=True
    username: root
    password: dfrt456A!sd

  jpa:
    hibernate:
      ddl-auto: update


#server:
#  servlet:
#    context-path: /admin
conf:
  sitesUrl:
    - http://www.playback.ru/
    - https://volochek.life/
    - http://radiomv.ru/
    - https://ipfran.ru/
    - https://dimonvideo.ru/
    - https://nikoartgallery.com/
    - https://et-cetera.ru/mobile/
    - https://www.lutherancathedral.ru/
    - https://dombulgakova.ru/
    - https://www.svetlovka.ru/

  sitesName:
    - Плейбек.ру
    - volochek
    - radiomv
    - ipfran
    - dimonvideo
    - nikoartgallery
    - et-cetera
    - lutherancathedral
    - dombulgakova
    - svetlovka
  userAgent: Mozilla/5.0 (Windows NT 6.1; rv:98.0) Gecko/20100101 Firefox/98.0
  referrer: http://google.com

#logging:
#  level:
#    org.springframework.web: trace
#    org.apache: trace